export default {
    ADD_OUTCOME: 'ADD_OUTCOME',
    REMOVE_OUTCOME: 'REMOVE_OUTCOME',
    BACKEND_CALL: 'BACKEND_CALL',
    ADD_OUTCOME_RESP: 'ADD_OUTCOME_RESP',
    REMOVE_OUTCOME_RESP: 'REMOVE_OUTCOME_RESP',
    BACKEND_CALL_RESP: 'BACKEND_CALL_RESP'
}