export default {
    GET_USER: 'GET_USER',
    GET_USER_RESP: 'GET_USER_RESP',
    ADD_OUTCOME: 'ADD_OUTCOME',
    REMOVE_OUTCOME: 'REMOVE_OUTCOME',
    BACKEND_CALL: 'BACKEND_CALL',
    ADD_OUTCOME_RESP: 'ADD_OUTCOME_RESP',
    REMOVE_OUTCOME_RESP: 'REMOVE_OUTCOME_RESP',
    BACKEND_CALL_RESP: 'BACKEND_CALL_RESP',
    LOAD_METADATA: 'LOAD_METADATA',
    LOAD_METADATA_RESP: 'LOAD_METADATA_RESP',
    GET_TESTCASES: 'GET_TESTCASES',
    GET_TESTCASES_RESP: 'GET_TESTCASES_RESP'
}